# -*- coding: utf-8 -*-

import datetime

from django.utils.translation import ugettext_lazy as _


# Datetime object representing time of last country list update.
COUNTRIES_LAST_UPDATE = datetime.datetime(2011, 7, 7, 18, 15)


# List of United Nation states (plus Vatican) and their ISO codes.
COUNTRIES = (
    # (
    #   '<ISO 3166-1 alpha-2 uppercase code>',
    #   _("<official English short name>")
    # ),
    ('AF', _("Afghanistan")),
    ('AL', _("Albania")),
    ('DZ', _("Algeria")),
    ('AD', _("Andorra")),
    ('AO', _("Angola")),
    ('AG', _("Antigua and Barbuda")),
    ('AR', _("Argentina")),
    ('AM', _("Armenia")),
    ('AU', _("Australia")),
    ('AT', _("Austria")),
    ('AZ', _("Azerbaijan")),
    ('BS', _("Bahamas")),
    ('BH', _("Bahrain")),
    ('BD', _("Bangladesh")),
    ('BB', _("Barbados")),
    ('BY', _("Belarus")),
    ('BE', _("Belgium")),
    ('BZ', _("Belize")),
    ('BJ', _("Benin")),
    ('BT', _("Bhutan")),
    ('BO', _("Bolivia")),
    ('BA', _("Bosnia and Herzegovina")),
    ('BW', _("Botswana")),
    ('BR', _("Brazil")),
    ('BN', _("Brunei Darussalam")),
    ('BG', _("Bulgaria")),
    ('BF', _("Burkina Faso")),
    ('BI', _("Burundi")),
    ('KH', _("Cambodia")),
    ('CM', _("Cameroon")),
    ('CA', _("Canada")),
    ('CV', _("Cape Verde")),
    ('CF', _("Central African Republic")),
    ('TD', _("Chad")),
    ('CL', _("Chile")),
    ('CN', _("China")),
    ('CO', _("Colombia")),
    ('KM', _("Comoros")),
    ('CG', _("Congo")),
    ('CR', _("Costa Rica")),
    ('CI', _("Cote D'ivoire")),
    ('HR', _("Croatia")),
    ('CU', _("Cuba")),
    ('CY', _("Cyprus")),
    ('CZ', _("Czech Republic")),
    ('KP', _("Democratic People's Republic of Korea")),
    ('CD', _("Democratic Republic of the Congo")),
    ('DK', _("Denmark")),
    ('DJ', _("Djibouti")),
    ('DM', _("Dominica")),
    ('DO', _("Dominican Republic")),
    ('EC', _("Ecuador")),
    ('EG', _("Egypt")),
    ('SV', _("El Salvador")),
    ('GQ', _("Equatorial Guinea")),
    ('ER', _("Eritrea")),
    ('EE', _("Estonia")),
    ('ET', _("Ethiopia")),
    ('FJ', _("Fiji")),
    ('FI', _("Finland")),
    ('FR', _("France")),
    ('GA', _("Gabon")),
    ('GM', _("Gambia")),
    ('GE', _("Georgia")),
    ('DE', _("Germany")),
    ('GH', _("Ghana")),
    ('GR', _("Greece")),
    ('GD', _("Grenada")),
    ('GT', _("Guatemala")),
    ('GN', _("Guinea")),
    ('GW', _("Guinea Bissau")),
    ('GY', _("Guyana")),
    ('HT', _("Haiti")),
    ('HN', _("Honduras")),
    ('HU', _("Hungary")),
    ('IS', _("Iceland")),
    ('IN', _("India")),
    ('ID', _("Indonesia")),
    ('IR', _("Iran, Islamic Republic of")),
    ('IQ', _("Iraq")),
    ('IE', _("Ireland")),
    ('IL', _("Israel")),
    ('IT', _("Italy")),
    ('JM', _("Jamaica")),
    ('JP', _("Japan")),
    ('JO', _("Jordan")),
    ('KZ', _("Kazakhstan")),
    ('KE', _("Kenya")),
    ('KI', _("Kiribati")),
    ('KW', _("Kuwait")),
    ('KG', _("Kyrgyzstan")),
    ('LA', _("Lao People's Democratic Republic")),
    ('LV', _("Latvia")),
    ('LB', _("Lebanon")),
    ('LS', _("Lesotho")),
    ('LR', _("Liberia")),
    ('LY', _("Libyan Arab Jamahiriya")),
    ('LI', _("Liechtenstein")),
    ('LT', _("Lithuania")),
    ('LU', _("Luxembourg")),
    ('MG', _("Madagascar")),
    ('MW', _("Malawi")),
    ('MY', _("Malaysia")),
    ('MV', _("Maldives")),
    ('ML', _("Mali")),
    ('MT', _("Malta")),
    ('MH', _("Marshall Islands")),
    ('MR', _("Mauritania")),
    ('MU', _("Mauritius")),
    ('MX', _("Mexico")),
    ('FM', _("Micronesia, Federated States of")),
    ('MC', _("Monaco")),
    ('MN', _("Mongolia")),
    ('ME', _("Montenegro")),
    ('MA', _("Morocco")),
    ('MZ', _("Mozambique")),
    ('MM', _("Myanmar")),
    ('NA', _("Namibia")),
    ('NR', _("Nauru")),
    ('NP', _("Nepal")),
    ('NL', _("Netherlands")),
    ('NZ', _("New Zealand")),
    ('NI', _("Nicaragua")),
    ('NE', _("Niger")),
    ('NG', _("Nigeria")),
    ('NO', _("Norway")),
    ('OM', _("Oman")),
    ('PK', _("Pakistan")),
    ('PW', _("Palau")),
    ('PA', _("Panama")),
    ('PG', _("Papua New Guinea")),
    ('PY', _("Paraguay")),
    ('PE', _("Peru")),
    ('PH', _("Philippines")),
    ('PL', _("Poland")),
    ('PT', _("Portugal")),
    ('QA', _("Qatar")),
    ('KR', _("Republic of Korea")),
    ('MD', _("Republic of Moldova")),
    ('RO', _("Romania")),
    ('RU', _("Russian Federation")),
    ('RW', _("Rwanda")),
    ('KN', _("Saint Kitts and Nevis")),
    ('LC', _("Saint Lucia")),
    ('VC', _("Saint Vincent and The Grenadines")),
    ('WS', _("Samoa")),
    ('SM', _("San Marino")),
    ('ST', _("Sao Tome and Principe")),
    ('SA', _("Saudi Arabia")),
    ('SN', _("Senegal")),
    ('RS', _("Serbia")),
    ('SC', _("Seychelles")),
    ('SL', _("Sierra Leone")),
    ('SG', _("Singapore")),
    ('SK', _("Slovakia")),
    ('SI', _("Slovenia")),
    ('SB', _("Solomon Islands")),
    ('SO', _("Somalia")),
    ('ZA', _("South Africa")),
    ('ES', _("Spain")),
    ('LK', _("Sri Lanka")),
    ('SD', _("Sudan")),
    ('SR', _("Suriname")),
    ('SZ', _("Swaziland")),
    ('SE', _("Sweden")),
    ('CH', _("Switzerland")),
    ('SY', _("Syrian Arab Republic")),
    ('TJ', _("Tajikistan")),
    ('TH', _("Thailand")),
    ('MK', _("The former Yugoslav Republic of Macedonia")),
    ('TL', _("Timor-Leste")),
    ('TG', _("Togo")),
    ('TO', _("Tonga")),
    ('TT', _("Trinidad and Tobago")),
    ('TN', _("Tunisia")),
    ('TR', _("Turkey")),
    ('TM', _("Turkmenistan")),
    ('TV', _("Tuvalu")),
    ('UG', _("Uganda")),
    ('UA', _("Ukraine")),
    ('AE', _("United Arab Emirates")),
    ('GB', _("United Kingdom")),
    ('TZ', _("United Republic of Tanzania")),
    ('US', _("United States")),
    ('UY', _("Uruguay")),
    ('UZ', _("Uzbekistan")),
    ('VU', _("Vanuatu")),
    ('VE', _("Venezuela, Bolivarian Republic of")),
    ('VN', _("Viet Nam")),
    ('YE', _("Yemen")),
    ('ZM', _("Zambia")),
    ('ZW', _("Zimbabwe")),
)

